// Extracts the two single-stroke Hershey fonts the reel uses (script for the signature, futural for plotter labels)
// from node_modules/hersheytext into src/hershey.js, as polylines per glyph: { o: half-advance, s: [[x,y,...], ...] }.
import { readFileSync, writeFileSync } from 'node:fs';
const all = JSON.parse(readFileSync('node_modules/hersheytext/hersheytext.json', 'utf8'));
const out = {};
for (const name of ['scripts', 'futural']) {
  out[name] = all[name].chars.map(({ d, o }) => {
    const strokes = [];
    for (const part of d.split('M').filter(Boolean)) {
      const nums = part.replace(/L/g, ' ').trim().split(/[\s,]+/).map(Number);
      strokes.push(nums);
    }
    return { o, s: strokes };
  });
}
writeFileSync('src/hershey.js', '// Generated by scripts/hershey.mjs from hersheytext (MIT). Hershey fonts are public domain.\nconst HERSHEY = ' + JSON.stringify(out) + ';\n');
console.log('wrote src/hershey.js', Object.keys(out).map(k => k + ':' + out[k].length));
